GroupProjectPage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('register.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings
from . import views


urlpatterns = [
    re_path(r'^image/(?P<path>.*)$', serve, {'document_root':
settings.MEDIA_ROOT}), #serve media files when deployed
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':
settings.STATIC_ROOT}), #serve static files when deployed
    path('', views.index, name='index'),
    path('movie_list/', views.MovieListView.as_view(), name='movie_list'),
    path('movie_detail/<int:pk>', views.MovieDetailView.as_view(), name='movie_detail'),
    path('director_list/', views.DirectorListView.as_view(), name='director_list'),
    path('director_detail/<int:pk>', views.DirectorDetailView.as_view(), name='director_detail'),
    path('moviereview_detail/<int:pk>', views.MovieReviewDetailView.as_view(), name='review_detail'),
    path('moviereview_list/', views.MovieReviewListView.as_view(), name='moviereview_list'),
    path('moviereview/create/', views.WriteMovieReviewByUser.as_view(), name='moviereview_create'),
    path('moviewreview/<int:pk>/update/', views.UpdateMovieReviewByUser.as_view(), name='moviereview_update'),
    path('moviewreview/<int:pk>/delete/', views.moviereview_delete, name='moviereview_delete'),
    path('profile/', views.view_profile, name='profile'),
    path('director/create/', views.DirectorCreate.as_view(), name='director_create'),
    path('director/<int:pk>/update/', views.DirectorUpdate.as_view(), name='director_update'),
    path('director/<int:pk>/delete/', views.director_delete, name='director_delete'),
    path('movie/create/', views.MovieCreate.as_view(), name='movie_create'),
    path('movie/<int:pk>/update/', views.MovieUpdate.as_view(), name='movie_update'),
    path('movie/<int:pk>/update/', views.movie_delete, name='movie_delete'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),

]

catalog/models.py
import django.db.models.deletion
from django.contrib.auth.decorators import permission_required
from django.db import models
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User # Used to authenticate User identity against Django default User model
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import date, time

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a movie genre (e.g. Sci-Fi or Horror)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Director(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    director_photo = models.ImageField(upload_to='image/', null=True, blank=True)

    class Meta:
        ordering = ['first_name', 'last_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('director_detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.first_name}, {self.last_name}'


class Movie(models.Model):
    """Model representing a movie made by a director."""
    title = models.CharField(max_length=200)

    # Foreign Key used because movie can only have one director, but directors can have multiple books
    director = models.ForeignKey('Director', on_delete=models.RESTRICT, null=True)

    description = models.TextField(max_length=1000, help_text='Enter a summary of the movie')
    # runtime used for formatting the run time of movie as ’00:00:00’
    runtime = models.TimeField()

    # ManyToManyField used because genre can contain many movies. Movies can cover many genres.
    genre = models.ManyToManyField(Genre, help_text='Select a genre(s) for this movie')

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('movie_detail', args=[str(self.id)])


class MovieReview(models.Model):
    """Model representing a review for a specific movie; to include a star rating out of 5."""
    caption = models.CharField(max_length=100)
    star_rating = models.IntegerField(default=1, validators=[MaxValueValidator(5), MinValueValidator(1)])  # add star image functionality
    review_text = models.TextField(max_length=300) # Review text

    # Foreign Keys to match movie review to a movie, and the profile leaving the review
    movie = models.ForeignKey('Movie', on_delete=models.RESTRICT, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.caption}: {self.star_rating}'


    def get_absolute_url(self):
        """Returns the URL to access a detail record for this review."""
        return reverse('review_detail', args=[str(self.id)])

class Profile(models.Model):
    # Pulls profile associated with user
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Attribute to store profile picture, and default to baseline .jpg file
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    # Area to write about the user on their profile
    about = models.CharField(max_length=300)
    # Set profile preferences
    preferences = models.ManyToManyField(Genre, help_text='Select your favorite genres of movies')

    def __str__(self):
        return f'{self.user.username} Profile'

catalog/views.py
from .models import Movie, Director, MovieReview, Genre
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Avg
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, request
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required



def index(request):
    """View function for home page of site."""
    num_movies = Movie.objects.all().count()
    num_reviews = MovieReview.objects.all().count()
    num_directors = Director.objects.all().count()

    # Average total star value
    num_average_rating = MovieReview.objects.aggregate(Avg('star_rating'))
    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_movies': num_movies,
        'num_reviews': num_reviews,
        'num_average_rating': num_average_rating,
        'num_directors': num_directors,
        'num_visits': num_visits,
    }
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'catalog/index.html', context=context)


class MovieListView(LoginRequiredMixin, generic.ListView):
    model = Movie

class MovieDetailView(LoginRequiredMixin, generic.DetailView):
    model = Movie

class MovieCreate(CreateView):
    model = Movie
    fields = ['title', 'director', 'description', 'runtime', 'genre']

class MovieUpdate(UpdateView):
    model = Movie
    fields = ['title', 'director', 'description', 'runtime', 'genre']

def movie_delete(request, pk):
    author = get_object_or_404(Movie, pk=pk)
    try:
        movie.delete()
        messages.success(request, (movie.title + ' ' + ' has been deleted. Associated reviews deleting.'))
    except:
        messages.success(request, (movie.title + ' ' + 'cannot be deleted.'))
    return redirect('movie_list')

class DirectorListView(LoginRequiredMixin, generic.ListView):
    model = Director

class DirectorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Director

class DirectorCreate(CreateView):
    model = Director
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death', 'director_photo']

class DirectorUpdate(UpdateView):
    model = Director
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death', 'director_photo']

def director_delete(request, pk):
    director = get_object_or_404(Director, pk=pk)
    try:
        director.delete()
        messages.success(request, (director.first_name + ' ' +
                                   director.last_name +" has been deleted"))
    except:
        messages.success(request, (director.first_name + ' ' + director.last_name + 'cannot be deleted. Movies exist '
                                                                                    'for the director'))
    return redirect('director_list')


class MovieReviewDetailView(LoginRequiredMixin, generic.DetailView):
    model = MovieReview

class MovieReviewListView(LoginRequiredMixin, generic.ListView):
    model = MovieReview


### Movie review create, update, and delete functionality in 2 classes and def below ###

class WriteMovieReviewByUser(CreateView):
    model = MovieReview
    fields = ['caption', 'star_rating', 'review_text']


class UpdateMovieReviewByUser(UpdateView):
    model = MovieReview
    fields = ['caption', 'star_rating', 'review_text']


def moviereview_delete(request, pk):
    moviereview = get_object_or_404(MovieReview, pk=pk)
    try:
        moviereview.delete()
        messages.success(request, (moviereview.user + "\'s review on" + moviereview.movie + " has been deleted!"))
    except:
        messages.success(request, (moviereview.user + '\'s review on' + moviereview.movie + ' cannot be deleted.'))
    return redirect('base')

@login_required
def view_profile(request):
    profile = request.user.profile
    preferences = profile.preferences.all()
    return render(request, 'catalog/profile.html', {'profile': profile, 'preferences': preferences})


@login_required
def edit_profile(request):
    profile = request.user.profile
    all_genres = Genre.objects.all()
    user_reviews = MovieReview.objects.filter(user=request.user)  # Fetch user's reviews

    if request.method == 'POST':
        bio = request.POST.get('bio')
        selected_preferences = request.POST.getlist('preferences')

        profile.about = bio
        profile.preferences.clear()
        profile.preferences.add(*Genre.objects.filter(id__in=selected_preferences))
        profile.save()

        messages.success(request, 'Profile updated successfully.')
        return redirect('profile')  # Redirect to profile view

    return render(request, 'catalog/profile.html', {
        'profile': profile,
        'all_genres': all_genres,
        'user_reviews': user_reviews  # Include user reviews in the context
    })

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Movie-Review.U{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
               body{
            background-image: url("image/camera.jpeg");
            background-position: center;
            margin: 0;
            padding: 0;
            color: white;
        }

    </style>
</head>
<body>
<!--- Start Navbar and Button display --->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Movie-Review.U</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'movie_list' %}">All Movies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'director_list' %}">All Directors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'moviereview_list' %}">Read Reviews</a>
                </li>
            </ul>

        </div>
       <!--Display Login/Logout right-justified in navbar and link to register as user-->
    <ul class="nav navbar-nav ml-auto">
        {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'profile'%}">View Profile</a></li>
            <li><a class="nav-link" href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span>Logout</a>
            </li>
            <li class="nav-item dropdown">
            </li>
            {% if user.is_superuser %}
                <ul class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                            Admin Functions
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'director_create' %}">Add Director</a></li>
                        <li><a class="dropdown-item" href="{% url 'movie_create' %}">Add Movie</a></li>
                        <li><a class="dropdown-item" href="{% url 'moviereview_create' %}">Add Review</a></li>
                    </ul>
            {% endif %}


        {% else %}
            <li><a class="nav-link" href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a>
            </li>

            <li><a class="nav-link" href="{% url 'register' %}"><span class="glyphicon glyphicon-log-in"></span>Sign Up</a>
            </li>

        {% endif %}
    </ul>

    </div>
</nav>
<!--- Container for User Welcome message --->
<div class="container">
    {% if user.is_authenticated %}
        Welcome, {{ user.first_name }} {{ user.last_name }}
    {% endif %}
</div>

<div class="container">
    <br/>
    {% block content %}

    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/director_delete.html
{% extends "catalog/base.html" %}
    <style>
               body{
            background-image: url("image/camera.jpeg");
            background-position: center;
            margin: 0;
            padding: 0;
             color: white;
        }
    </style>
{% block content %}
    {% if perms.catalog.delete_director %}
        <h1>Delete Director {{ director.first_name }}</h1>
        <form method="Post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
            <a href="{% url 'index' pk=director.id %} ">Cancel</a>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}

catalog/templates/catalog/director_detail.html
{% extends "catalog/base.html" %}
{% block content %}
    <style>
               body{
            background-image: url("image/camera.jpeg");
            background-position: center;
            margin: 0;
            padding: 0;
             color: white;
        }
    </style>
    <h1>Name: {{ director.first_name }} {{ director.last_name }}</h1>

        <p><strong>Date of Birth:</strong> {{ director.date_of_birth }}</p>
        <p><strong>Date of Death:</strong> {{ director.date_of_death }}</p>
    <div>
        {% if director.director_photo %}
            <img src="{{ director.director_photo.url }}">
        {% endif %}
    </div>
    <div style="margin-left:20px;margin-top:20px">
    <hr>
        <p><strong><a href="{%  url 'director_list' %} "> Return to Director List </a></strong>
    </p>
    </div>
{% endblock %}

catalog/templates/catalog/director_form.html
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
    <style>
               body{
            background-image: url("image/camera.jpeg");
            background-position: center;
            margin: 0;
            padding: 0;
             color: white;
        }
    </style>
{% block content %}
    {% if perms.catalog.create_director or perms.catalog.edit_director %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit"/>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}

catalog/templates/catalog/director_list.html
{% extends "catalog/base.html" %}
{% block content %}
        <style>
               body{
            background-image: url("image/camera.jpeg");
            background-position: center;
            margin: 0;
            padding: 0;
             color: white;
        }
    </style>
    <h1>Director List</h1>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

        {% endfor %}
    {% endif %}
    {% if director_list %}
        <table class="table table-bordered">
            {% for director in director_list %}
                <tr class="table-secondary">
                    <td><a href="{{ director.get_absolute_url }}">{{ director.first_name }} {{ director.last_name }}</a></td>

                    {% if user.is_superuser %}
                        {% if director.movie_set.all %}
                            <td>Movies Exist - Cannot delete director</td>
                        {% else %}
                            <td><a href="{% url 'director_delete' pk=director.pk %}"
                                   onclick="return confirm('Are you sure you want to delete?')"
                                   class="btn btn-danger">Delete</a>
                            </td>
                        {% endif %}
                        <td><a href="{% url 'director_update' pk=director.pk %}" class="btn btn-primary">Edit Director</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>There are no directors displayable at the moment.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Movie-Review.U</title>
    <style>
               body{
            background-image: url("image/camera.jpeg");
            background-position: center;
            margin: 0;
            padding: 0;
             color: white;
        }
    </style>
</head>
<body>

<div class="container">
    <h1>Movie-Review.U</h1>

</div>

</body>
</html>

{% block content %}
  <h1>Movie-Review.U Homepage</h1>
  <p>Review our catalog of the best:</p>
    <h2>Movies | Directors | Reviews</h2>
  <ul>
    <li><strong>Movies:</strong> {{ num_movies }}</li>
    <li><strong>Movie Reviews:</strong> {{ num_reviews }}</li>
    <li><strong>Directors:</strong> {{ num_directors }}</li>
  </ul>
    <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>
{% endblock %}

catalog/templates/catalog/movie_form.html
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
    <style>
               body{
            background-image: url("image/camera.jpeg");
            background-position: center;
            margin: 0;
            padding: 0;
             color: white;
        }
    </style>
{% block content %}
    {% if perms.catalog.create_movie or perms.catalog.edit_movie %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit"/>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}

catalog/templates/catalog/moviereview_delete.html
{% extends "catalog/base.html" %}
{% block content %}
        <style>
               body{
            background-image: url("image/camera.jpeg");
            background-position: center;
            margin: 0;
            padding: 0;
             color: white;
        }
    </style>
    {% if perms.catalog.review_delete %}
        <h1>Delete Movie Review {{ moviereview.caption }}</h1>
        <form method="Post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
            <a href="{% url 'index' pk=moviereview.id %} ">Cancel</a>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}

catalog/templates/catalog/moviereview_detail.html
{% extends "catalog/base.html" %}
{% block content %}
        <style>
               body{
            background-image: url("image/camera.jpeg");
            background-position: center;
            margin: 0;
            padding: 0;
             color: white;
        }
    </style>
    <h1>{{ moviereview.caption }}</h1>
        <br>
        <h4>{{ moviereview.star_rating }}</h4>
        <p>{{ moviereview.review_text }}</p>
        <br>
        <br>
        <li><i>Left by {{ moviereview.user }}</i></li>
    <div style="margin-left:20px;margin-top:20px">
        <hr>
        <p><strong><a href="{% url 'moviereview_list' %}"> See Reviews </a></strong>
        </p>
        <p><strong><a href="{{ moviereview.movie.get_absolute_url }}"> See Movie </a></strong>
        </p>
    </div>
{% endblock %}

catalog/templates/catalog/moviereview_form.html
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
    <style>
               body{
            background-image: url("image/camera.jpeg");
            background-position: center;
            margin: 0;
            padding: 0;
            color: white;
        }
    </style>

{% block content %}
    {% if perms.catalog.create_moviereview or perms.catalog.edit_moviereview %}
        <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}

            <input type="submit" value="Submit"/>
        </form>
    {% else %}
        You cannot post a review with current credentials.
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}

catalog/templates/catalog/moviereview_list.html
{% extends "catalog/base.html" %}
{% block content %}
        <style>
               body{
            background-image: url("image/camera.jpeg");
            background-position: center;
            margin: 0;
            padding: 0;
             color: white;
        }
    </style>
    <h1>All Reviews</h1>
        {% if moviereview_list %}
            <ul>
                {% for movie in moviereview_list %}
                    <li>
                       <a href="{{ movie.get_absolute_url }}"><p>{{ movie.caption }}<p></a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>There are no movies reviewed yet.</p>
        {% endif %}
{% endblock %}

catalog/templates/catalog/profile.html
{% extends "catalog/base.html" %}

{% block content %}
<div style="background-color: #fff; padding: 30px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin: 20px; color: black;">
    <div style="display: flex; align-items: center; margin-bottom: 20px;">
        <img src="{{ profile.image.url }}" alt="Profile Picture" style="width: 150px; height: 150px; border-radius: 50%; border: 3px solid #ddd; margin-right: 20px;">
        <div>
            <h2 style="margin: 0; color: black;">{{ profile.user.get_full_name }}</h2>
            <p style="color: black; font-style: italic;">{{ profile.about }}</p>
        </div>
    </div>
    </div>
    <div style="margin-top: 20px;">
        <h3 style="color: #333; margin-bottom: 10px;">Preferences</h3>
        <ul style="list-style: none; padding: 0;">
            {% for genre in profile.preferences.all %}
                <li style="margin: 5px 0; padding: 8px; background-color: #f8f8f8; border-left: 4px solid #007bff;">{{ genre.name }}</li>
            {% endfor %}
        </ul>
    </div>



    <!-- Edit Profile Button -->
    <button onclick="toggleEditForm()" style="background-color: #007bff; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; margin-top: 20px;">Edit Profile</button>
</div>

<!-- Edit Form ( Hidden) -->
<div id="editForm" style="display: none; background-color: #fff; padding: 30px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin: 20px;">
    <form method="post" action="{% url 'edit_profile' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div style="margin-bottom: 20px;">
            <label for="id_bio" style="display: block; margin-bottom: 10px;">Bio:</label>
            <textarea name="bio" id="id_bio" style="width: 100%; border: 1px solid #ddd; border-radius: 4px; padding: 10px;">{{ profile.about }}</textarea>
        </div>
        <div style="margin-bottom: 20px;">
            <label for="id_preferences" style="display: block; margin-bottom: 10px;">Preferences:</label>
            <select name="preferences" id="id_preferences" multiple style="width: 100%; border: 1px solid #ddd; border-radius: 4px; padding: 10px;">
                {% for genre in all_genres %}
                    <option value="{{ genre.id }}" {% if genre in profile.preferences.all %}selected{% endif %}>{{ genre.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div style="text-align: right;">
            <input type="submit" value="Update Profile" style="background-color: #007bff; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer;">
        </div>
    </form>
</div>
<!-- User's Reviews Section -->
<div style="margin-top: 20px;">
    <h3>User's Reviews</h3>
    {% for review in user_reviews %}
        <div>
            <p>Review for Movie: {{ review.movie.title }}</p>
            <p>Rating: {{ review.star_rating }}</p>
            <p>Comment: {{ review.review_text }}</p>
        </div>
    {% empty %}
        <p>No reviews yet.</p>
    {% endfor %}
</div>

<script>
function toggleEditForm() {
    var form = document.getElementById('editForm');
    if (form.style.display === 'none' || form.style.display === '') {
        form.style.display = 'block';
    } else {
        form.style.display = 'none';
    }
}
</script>
{% endblock %}

catalog/templates/catalog/review_delete.html
{% extends "catalog/base.html" %}

{% block content %}
    {% if perms.catalog.review_delete %}
        <h1>Delete Movie Review {{ moviereview.caption }}</h1>
        <form method="Post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
            <a href="{% url 'index' pk=moviereview.id %} ">Cancel</a>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}

catalog/templates/catalog/review_form.html
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
    {% if perms.catalog.create_review or perms.catalog.edit_review %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit"/>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}